[template]
exclude = ["target/", ".git/", "Cargo.lock","cliff.toml"]

[placeholders]
gh-username = { type = "string", prompt = "GitHub username?" }
project-description = { type = "string", prompt = "Project description?", default = "A Rust project" }
